platform :ios, '10.0'
# Muti Project
# install! 'cocoapods', generate_multiple_pod_projects: true



target 'Shorthair' do
  use_frameworks!
  use_modular_headers!
  pod 'SnapKit', '~> 4.2.0'
  pod 'YYText', '~> 1.0.4'
end

target 'Shorthair-Sample' do
  pod 'Shorthair', :path => "../"
end

