platform :ios, '10.0'
# Muti Project
# install! 'cocoapods', generate_multiple_pod_projects: true
install! 'cocoapods', :disable_input_output_paths => true
inhibit_all_warnings!


target 'Shorthair' do
  use_frameworks!
  pod 'SnapKit', '~> 4.2.0'
  pod 'YYText', '~> 1.0.4'
  pod 'YYAsyncLayer', '~> 1.0'
  pod 'TTTAttributedLabel', '~> 2.0'
  pod 'MMMarkdown'
  pod 'DTCoreText'
  pod "Atributika"
end

target 'Shorthair-Sample' do
  use_frameworks!
#  pod 'Shorthair', :path => "../"
end

